// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StaffShiftService.Database;

namespace StaffShiftService.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210419014658_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StaffShiftService.Database.Entites.StaffShift", b =>
                {
                    b.Property<int>("ShiftID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ExtraHours")
                        .HasColumnType("int");

                    b.Property<DateTime>("OverTimeDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("OvertimeMultiplier")
                        .HasColumnType("real");

                    b.Property<int>("StaffID")
                        .HasColumnType("int");

                    b.HasKey("ShiftID");

                    b.ToTable("StaffShifts");
                });
#pragma warning restore 612, 618
        }
    }
}
